modLoader="javafml" #mandatory
loaderVersion="[43,)"
license="MIT"
[[mods]] #mandatory
modId="remnantsofcuriosity" #mandatory
version="1.0" #mandatory
displayName="Remnants Of Curiosity" #mandatory
logoFile="remnantsofcuriosity.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="MissileMan" #optional
description='''
Find new curios, which are remnants of a past civilazation.
'''
[[dependencies.remnantsofcuriosity]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.remnantsofcuriosity]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.remnantsofcuriosity]]
    modId="curios"
    mandatory=true
    versionRange="[1.19.2-5.1.1.0,)"
